spring:
  application:
    name: eureka-server-clustered
  profiles: peer1
server:
  port: ${PORT:8761}
    
eureka:  
  instance:
    hostname: localhost
    #instance-id:  ${spring.cloud.client.ipAddress}:${server.port}      # 将Instance ID设置成IP:端口的形式
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/,http://localhost:8763/eureka/
#      defaultZone: http://${server.host}:8762/eureka/,http://${server.host}:8763/eureka/

  server:
    enableSelfPreservation: true


---
    spring:
      application:
        name: eureka-server-clustered
      profiles: peer2

    server:
      port: ${PORT:8762}

    eureka:
      instance:
        hostname: localhost
        #instance-id:  ${spring.cloud.client.ipAddress}:${server.port}        # 将Instance ID设置成IP:端口的形式
        prefer-ip-address: true
      client:
        registerWithEureka: true
        fetchRegistry: false
        serviceUrl:
          defaultZone: http://localhost:8761/eureka/,http://localhost:8763/eureka/
      server:
        enableSelfPreservation: true

---
spring:
  application:
    name: eureka-server-clustered
  profiles: peer3
server:
  port: ${PORT:8763}

eureka:
  instance:
    hostname: localhost
    #instance-id:  ${spring.cloud.client.ipAddress}:${server.port}        # 将Instance ID设置成IP:端口的形式
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
  server:
    enableSelfPreservation: true